Added stat module
jetporch/jetporch pull request #11
Opened 2023-09-30 21:00 UTC by jilleJr

Adds a new module: `!stat`

Example usage:

```yaml
- name: stat playbook
  groups: [all]
  tasks:
    - !stat
      name: stat current directory
      path: .
      save: stat1

    - !echo
      msg: |

        Stat output:
          exists: {{ stat1.exists }}
          {{#if stat1.exists }}
          is_dir: {{ stat1.is_dir }}
          mode: {{ stat1.mode }}
          size: {{ stat1.size }} (bytes)
          owner: {{ stat1.owner }}
          group: {{ stat1.group }}
          {{/if}}

    - !stat
      name: stat /bin/bash
      path: /bin/bash
      save: stat2

    - !echo
      msg: |

        Stat output:
          exists: {{ stat2.exists }}
          {{#if stat2.exists }}
          is_dir: {{ stat2.is_dir }}
          mode: {{ stat2.mode }}
          size: {{ stat2.size }} (bytes)
          owner: {{ stat2.owner }}
          group: {{ stat2.group }}
          {{/if}}

    - !stat
      name: stat non-existing-file.txt
      path: non-existing-file.txt
      save: stat3

    - !echo
      msg: |

        Stat output:
          exists: {{ stat3.exists }}
          {{#if stat3.exists }}
          is_dir: {{ stat3.is_dir }}
          mode: {{ stat3.mode }}
          size: {{ stat3.size }} (bytes)
          owner: {{ stat3.owner }}
          group: {{ stat3.group }}
          {{/if}}
```

```console
$ jetp local -p playbooks/stat-playbook.yml
----------------------------------------------------------
> playbook start: /home/kalle/code/jetp-testing/playbooks/stat-playbook.yml
----------------------------------------------------------
> play: stat playbook
----------------------------------------------------------
> batch 1/1, 1 hosts
----------------------------------------------------------
> begin task: stat current directory
… localhost => running
----------------------------------------------------------
> begin task: echo
… localhost => running
  ..... localhost :
Stat output:
  exists: true
  is_dir: true
  mode: 755
  size: 4096 (bytes)
  owner: kalle
  group: kalle

----------------------------------------------------------
> begin task: stat /bin/bash
… localhost => running
----------------------------------------------------------
> begin task: echo
… localhost => running
  ..... localhost :
Stat output:
  exists: true
  is_dir: false
  mode: 755
  size: 1431840 (bytes)
  owner: root
  group: root

----------------------------------------------------------
> begin task: stat non-existing-file.txt
… localhost => running
----------------------------------------------------------
> begin task: echo
… localhost => running
  ..... localhost :
Stat output:
  exists: false

----------------------------------------------------------
> play complete: stat playbook
----------------------------------------------------------

┌─────────┬─────┬─────┐
│Results  │Items│Hosts│
├─────────┼─────┼─────┤
│Roles    │0    │     │
│Tasks    │6    │1    │
├─────────┼─────┼─────┤
│Matched  │0    │0    │
│Created  │0    │0    │
│Modified │0    │0    │
│Removed  │0    │0    │
│Executed │0    │0    │
│Passive  │6    │1    │
│Skipped  │0    │0    │
├─────────┼─────┼─────┤
│Unchanged│6    │1    │
│Changed  │0    │0    │
│Failed   │0    │0    │
└─────────┴─────┴─────┘

(✓) Perfect. All hosts matched policy.
```

2023-09-30 21:03 UTC, jilleJr commented on src/modules/files/stat.rs
> +                    },
Question is, should it always output these variables and then have some defaults, or should it do thing thing where only some variables are set?

What about setting the values to `serde_yaml::Value::Null`?

2023-09-30 21:27 UTC, mpdehaan commented
thanks for this, added some comments, I think the big one is checking mode first, handling the non-directory case and directory case equally), and using a struct to hold the output before asking serde to serialize it, versus building the struct up in pieces, that way we can make sure the struct is consistent with types and things like Option\<type\> make sure the values that are undefined are always there in each leg.  More type checking and consistency checking from serde and the compiler, etc.  Similarly, I generally try to avoid unwrap_err and try to make things more explicit, I think moving to first match on the "exists/doesn't exist" with the mode check will help.

2023-10-01 00:03 UTC, jilleJr commented
@mpdehaan thanks for the review!

I think I've implemented your suggestions.

2023-10-01 18:00 UTC, mpdehaan commented
I may have commented on the old versions, let me try clicking on this again, I think I got messed up with the force push you made.

2023-10-01 18:01 UTC, mpdehaan commented
Nope, nevermind, I think the comments are on the new versions.  Sorry, still getting used to github for code review. Let me know if that makes sense, thanks!.

2023-10-01 18:27 UTC, jilleJr commented
> I may have commented on the old versions, let me try clicking on this again, I think I got messed up with the force push you made.

Yea really hard to know which maintainers require rebases and which not. I take it you may not have that preference?



> Nope, nevermind, I think the comments are on the new versions. Sorry, still getting used to github for code review. Let me know if that makes sense, thanks!.

I don't know which comments you're referring to. Maybe you haven't submitted your review comments, and they're still pending?

2023-10-01 18:50 UTC, mpdehaan commented
> Yea really hard to know which maintainers require rebases and which not. I take it you may not have that preference?

While I used to want to see rebases with ansible in the past, it was really frustrating to both ask and have people do it, and ultimately, I never really look at the history.  Code keeps changing, people keep asking for it, so  yeah, I don't really care about it.  

> I don't know which comments you're referring to. Maybe you haven't submitted your review comments, and they're still pending?

Sorry, I thought I replied to an older set of commits and I think I was replying to the new ones.  We're good on that.

2023-10-01 20:23 UTC, jilleJr commented
> > I don't know which comments you're referring to. Maybe you haven't submitted your review comments, and they're still pending?
> 
> Sorry, I thought I replied to an older set of commits and I think I was replying to the new ones. We're good on that.

Alright, so any further comments on the code? Or ready to merge?

2023-10-01 21:13 UTC, mpdehaan commented
Can you see these comments I made?

This is what I referred to before as possibly being hidden - https://github.com/jetporch/jetporch/pull/11/files#diff-c801ea6246f1ccf81426b99ca98d0d5ef52f6d31250b254eff8ba2a76b370404

Thanks!

2023-10-01 21:44 UTC, jilleJr commented
> Can you see these comments I made?
> 
> This is what I referred to before as possibly being hidden - https://github.com/jetporch/jetporch/pull/11/files#diff-c801ea6246f1ccf81426b99ca98d0d5ef52f6d31250b254eff8ba2a76b370404
> 
> Thanks!

Nope. That link just links to the `src/modules/files/stat.rs` file, and there's no comments there except for my initial one.

If you've added review comments on the "Files changed" page, then you must click the green "Review changes" button at the top right to submit your comments.

2023-10-01 22:10 UTC, mpdehaan requested changes

2023-10-01 22:12 UTC, mpdehaan commented
Ok I just submitted what I had before, should be good now!

2023-10-01 22:13 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                        let ownership = handle.remote.get_ownership(request, &self.path)?.unwrap_or((String::from(""), String::from("")));
this is mostly cleaned up if you look at the other comment that says "pardon the pseudocode here" ...

2023-10-02 06:24 UTC, jilleJr commented on src/modules/files/stat.rs
> +                _ => Err(handle.response.is_failed(request, &String::from("failed reading all stats for file. Possible the file just got removed?")))
Well since obtaining the data isn't atomic, then there is this potential race condition that this Err branch checks for.

What do you think should happen in this partially ok/partially bad case?

2023-10-02 10:43 UTC, mpdehaan commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
Running 3 commands isn't slow by anyone's standards with the SSH connection kept open, so I'm not worrying about that.

However, it does seem that your size function only reports a meaningful result on files, and on directories is going to report how much the directory /entry/ takes up, which is constant?  If so, that's not going to be meaningful and it would be better if in the directory case it runs the correct du command instead.  

I would suggest changing the "get_size" function in command library to take an "is_directory" parameter.

2023-10-02 10:46 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                _ => Err(handle.response.is_failed(request, &String::from("failed reading all stats for file. Possible the file just got removed?")))
If you are always running Checked versions of commands it's ok to let it fail naturally from the command code as you will see those commands fail and get the proper OS error.

(not sure if you know this from Rust things, I'll assume you do, if not, no offense intended ... run the command "Checked" and add the "?" on the end and it will bubble any error up to the calling function)

We do this quite a lot in the package management modules and such, it's a super unlikely scenario for a directory to go away while running and would be clear enough from the command failure output.

2023-10-02 17:12 UTC, jilleJr commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
It's not constant across filesystems. And its very standard to always have the size available in stat commands across different systems.

As a user, I would just expect the `!stat` module to be a wrapper around the stat command, and not to add its own business logic

2023-10-02 17:46 UTC, mpdehaan commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
"It's not constant across filesystems." - what is "it" here?  du?  The directory size on directories is not useful.

"!stat" - perhaps it should be renamed to file_info or something instead

2023-10-02 18:35 UTC, jilleJr commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
"it" referring to the stat size. The size in bytes for a file/directory is up to the filesystem to define.

For example, in my WSL instance running ext4, I get:

```console
$ stat --format %s empty-dir/
4096

$ stat --format %s dir-with-4000-files/
131072
```

Or in my Linux VM in VirtalBox running xfs, I get:

```console
$ stat --format %s empty-dir/
6

$ stat --format %s dir-with-4000-files/
98304
```

I don't make use of this value for directories in my daily work, but some may.

If you want it to behave a certain way, then renaming it to `!file_info` would be wise, to try to avoid expectations. Let me know if you really want to go that route, but personally, I highly advice against it, and just sticking with as plain values as possible.

2023-10-02 18:45 UTC, mpdehaan commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
I *know* that the value isn't useful, and don't really want to have an argument about it being useful in some theoretical playbook that doesn't exist :)  

The only useful thing with a size in bytes.

Acceptance criteria is either to remove the size code or make it call du correctly in the case of being given a directory.

2023-10-02 19:01 UTC, jilleJr commented on src/registry/list.rs
> +            Task::Stat(x)        => x.get_name(),
_in the court?_

I've reordered the items, but they were already unordered. Should I revert and only put `Stat` where it should be, and leave the other out-of-order?

2023-10-02 19:04 UTC, jilleJr commented on src/modules/files/stat.rs
> +                        let ownership = handle.remote.get_ownership(request, &self.path)?.unwrap_or((String::from(""), String::from("")));
Outdated comment. I think this is resolved.

2023-10-02 19:04 UTC, jilleJr commented on src/modules/files/stat.rs
> +                let is_dir = handle.remote.get_is_directory(request, &self.path);
Outdated comment. I think this is resolved.

2023-10-02 19:06 UTC, jilleJr commented on src/modules/files/stat.rs
> +                        let mode = handle.remote.get_mode(request, &self.path)?.unwrap_or(String::from(""));
Outdated comment. I think this is resolved.

2023-10-02 19:19 UTC, jilleJr commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
Yessir.

Changed

2023-10-02 19:40 UTC, mpdehaan commented
Since github doesn't really let me comment on the full "file" version is there a possibility of getting this resubmitted as a squashed PR in 1 commit?

On the subject of file size I meant remove it altogether or run the directory size for both, I want to avoid the template problem where some variable isn't defined in certain cases.

2023-10-02 19:41 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                    Err(x) => Err(handle.response.is_failed(request, &format!("failed serializing stat results: {}", x))),
At this point I'd need to see what this looks like in a squashed commit, probably, as I'm getting a bit lost.

But I think my earlier comment was if written correctly save_results should not be failing, it is the commands that should be failing.

2023-10-02 19:42 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                _ => Err(handle.response.is_failed(request, &String::from("failed reading all stats for file. Possible the file just got removed?")))
This is probably easiest if I look at a single commit squashed PR here too, as I don't really understand the question above.

2023-10-02 19:43 UTC, mpdehaan commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
per below, I meant remove size in both places or call du in the directory case.

2023-10-02 20:10 UTC, jilleJr commented
> Since github doesn't really let me comment on the full "file" version is there a possibility of getting this resubmitted as a squashed PR in 1 commit?
> 
> On the subject of file size I meant remove it altogether or run the directory size for both, I want to avoid the template problem where some variable isn't defined in certain cases.

Make sure you're looking at all changes, and then you get the full "file" version. I.e, go to https://github.com/jetporch/jetporch/pull/11/files instead of https://github.com/jetporch/jetporch/pull/11/commits/4db2700e63312212ea847560da600bf92e31bcc6, or in the top left click on the blue "Changes from 1 commit" and change to "Show all changes"

![image](https://github.com/jetporch/jetporch/assets/2477952/18ecef80-07c5-4ec9-b951-c547a465027c)

But sure, I'll rebase it

2023-10-02 20:14 UTC, jilleJr commented on src/modules/files/stat.rs
> +            match (is_dir_result, size_result, ownership_result) {
Removed

2023-10-02 20:14 UTC, mpdehaan requested changes
Did find the file view thanks to help in chat, this should be easier to comment on things now

2023-10-02 20:14 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                match serde_yaml::to_value(stat) {
save_results(...)? would be cleaner here, do all the YAML stuff inside the save_results function

2023-10-02 20:14 UTC, mpdehaan commented on src/modules/files/stat.rs
> +const NON_EXISTING_RESULT: StatResult = StatResult{
I'd name this DOESNT_EXIST

2023-10-02 20:14 UTC, mpdehaan commented on src/modules/files/stat.rs
> +    pub is_dir: Option<bool>,
perhaps overthinking this, but if it's Option<bool> someone has to contend with the value being None potentially, when a file that does not exist is not a directory, perhaps false is fine.

2023-10-02 20:14 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                match serde_yaml::to_value(stat) {
correction on previous comment -  it looks like it's impossible for stat_file to return an object that can't be YAML?

2023-10-02 20:14 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                    size: None,
per above comments, take this out of the struct for everything (and let someone else add it back later) or calculate it, either way.  It being None sort of sticks out.

2023-10-02 20:14 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                        None => Ok(NON_EXISTING_RESULT),
a 0 length file still exists so this should be removable.

2023-10-02 20:14 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                _ => Ok(NON_EXISTING_RESULT),
we're allowing the mode to fail rather than requiring every single step to decide whether the file now exists or not, so I think this part can be removed, just let the error bubble up if it happens in the middle of the module call.  It's arguable but I think its' better to know something weird happened in the module run anyway, than it trying to reflect a changing state during execution.... ie.. let it fail rather than returning that it does't exist.

2023-10-02 20:14 UTC, jilleJr commented on src/modules/files/stat.rs
> +                _ => Err(handle.response.is_failed(request, &String::from("failed reading all stats for file. Possible the file just got removed?")))
Possibly no longer relevant now with size removed.

2023-10-02 20:25 UTC, jilleJr commented on src/modules/files/stat.rs
> +const NON_EXISTING_RESULT: StatResult = StatResult{
Renamed

2023-10-02 20:25 UTC, jilleJr commented on src/modules/files/stat.rs
> +    pub is_dir: Option<bool>,
Makes sense to me.

Changed.

2023-10-02 20:25 UTC, jilleJr commented on src/modules/files/stat.rs
> +                match serde_yaml::to_value(stat) {
Depends on your definition. At the current state, no. But do we take that assumption, and add an `.unwrap()`, or is there a way to statically validate this at compile time?

2023-10-02 20:25 UTC, jilleJr commented on src/modules/files/stat.rs
> +                _ => Ok(NON_EXISTING_RESULT),
Fail in what way? As an error or as a panic?

2023-10-02 20:25 UTC, jilleJr commented on src/modules/files/stat.rs
> +                        None => Ok(NON_EXISTING_RESULT),
Nothing is checking the length of the file. What are you referring to that could be removed?

2023-10-02 20:25 UTC, jilleJr commented on src/modules/files/stat.rs
> +                    size: None,
Removed.

2023-10-02 20:34 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                _ => Ok(NON_EXISTING_RESULT),
The command modules will fail all the way up to Arc<TaskResponse> when they have non-zero return codes if they are executed as Checked

2023-10-02 20:36 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                        None => Ok(NON_EXISTING_RESULT),
ok that may have been before you updated it, it appeared to be some code that would return do not exist but I think it was because of the intermediate checks along the way (one of the three NON_EXISTING_RESULT paths)

2023-10-02 20:36 UTC, mpdehaan commented on src/modules/files/stat.rs
> +    pub is_dir: Option<bool>,
thanks!

2023-10-02 20:39 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                match serde_yaml::to_value(stat) {
I guess what i'm trying to say is move the call to serde_yaml::to_value(stat) inside of save_result and then let save result return the error of the right type, so that we can just do a save_result(...)?

2023-10-02 20:41 UTC, jilleJr commented on src/modules/files/stat.rs
> +                _ => Ok(NON_EXISTING_RESULT),
I mean like, do `Err(...)` instead of `Ok(...)` so it's just an error, or on the line with `handle.remote.get_ownership(...)?` should I add an `.unwrap()` at the end and treat it like a panic?

2023-10-02 20:42 UTC, jilleJr commented on src/modules/files/stat.rs
> +                        None => Ok(NON_EXISTING_RESULT),
Well if you find it again just make a new comment. Marking this one as resolved.

2023-10-02 20:46 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                _ => Ok(NON_EXISTING_RESULT),
I feel like I'm making you change too many things and am willing to tweak this one if I'm bad at explaining.  It's like swapping a couple of lines around and I'm happy to do that to make you not have to work on this repeatedly :)

On panics, no, the code should always return Err(...) and never panic inside of modules.  A panic in one thread will kill all the other threads.

2023-10-02 20:49 UTC, jilleJr commented on src/modules/files/stat.rs
> +                match serde_yaml::to_value(stat) {
Alright I'll change it back.

2023-10-02 20:52 UTC, jilleJr commented on src/modules/files/stat.rs
> +                _ => Ok(NON_EXISTING_RESULT),
Then yes please. Commit to this PR or just merge and fix later.

I'm quite drained from fixing this PR.

2023-10-02 20:56 UTC, mpdehaan commented on src/modules/files/stat.rs
> +                _ => Ok(NON_EXISTING_RESULT),
Yeah that is what I was trying to warn people about in the contrib guide :)  Appreciate the work and can change remaining easy bits.

2023-10-02 22:12 UTC, mpdehaan commented
got it merged, thanks for putting up with all of that, it was in really great shape

I removed a few warnings and made some small tweaks that were mostly preference related, I think the handling on the file being deleted halfway was a good call

I'll add documentation for this right now!  Thanks again!

2023-10-02 22:12 UTC, closed without merging