Added architecture detection
jetporch/jetporch pull request #12
Opened 2023-10-01 14:37 UTC by tonk

As a first attempt to code in Rust :-)
I added remote host architecture detection

2023-10-01 17:02 UTC, pcarinhas requested changes

2023-10-01 17:02 UTC, pcarinhas commented on src/modules/control/facts.rs
> +        return Ok(());
This should just be:

`Ok(())`

2023-10-01 17:05 UTC, pcarinhas commented on src/modules/control/facts.rs
> +        for line in out.lines() {
Why does uname have mulitple lines?

2023-10-01 17:32 UTC, tonk commented on src/modules/control/facts.rs
> +        return Ok(());
OK. I just "stole" that from some lines up :-)

2023-10-01 17:35 UTC, tonk commented on src/modules/control/facts.rs
> +        for line in out.lines() {
Very fair question.

It doesn't, but as I already told @mpdehaan my Rust skills are not up to scratch yet. I couldn't find a way to get a single line out of `out.lines()` any other way. So I copied the code from above,

2023-10-01 17:39 UTC, mpdehaan commented on src/modules/control/facts.rs
> +        return Ok(());
@pcarinhas please leave pull request review to me, thank you

2023-10-01 17:39 UTC, mpdehaan commented on src/modules/control/facts.rs
> +        return Ok(());
@tonk - that return is fine, I think it increases readability and I'm not worried about it.

2023-10-01 22:28 UTC, mpdehaan requested changes

2023-10-02 08:45 UTC, tonk commented
I have added the `line.trim()` .
Do you want a rebase on this?

2023-10-02 10:39 UTC, mpdehaan requested changes

2023-10-02 10:39 UTC, mpdehaan commented on src/modules/control/facts.rs
>          for line in out.lines() {
remove for loop

2023-10-02 10:39 UTC, mpdehaan commented
I think it's been too long since I've used git so I don't really see a point in the rebase, Squashing it into one commit would be nice

Looks like you still have the for loop in there though, the suggestion was to get rid of the for loop?  If that's gone, I apologize and it's the result

2023-10-02 12:10 UTC, tonk commented
Removed the `for` loop

2023-10-02 15:59 UTC, merged

2023-10-02 16:00 UTC, mpdehaan commented
merged in, didn't need the trim after all as the code removes the last newline in the connection, also arch is now returned on OS X as well.

Thanks!!!!