Introduce Zypper (package manager modules
jetporch/jetporch pull request #13
Opened 2023-10-01 23:29 UTC by bltavares

This commit introduces the Zypper package manager in order to use it with OpenSUSE systems.

It is based on the APT module, and includes some minor refactorings and code styles that could be ported back to APT on another PR.

There are tests to validate Zypper parsing.

2023-10-01 23:48 UTC, mpdehaan requested changes

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +    ) -> Result<EvaluatedTask, Arc<TaskResponse>> {
I know this is kind of personal, but I'd prefer to see all these lines kept short rather than expanding all the parameters out on single lines.  From past experience when starting a new module, someone always copies a *random* module, so if they are not kept consistent quickly they diverge and have no consistency.  Thanks!

For a concerete example, it's harder to review how all the arguments are processed differently when it's broken up over so many lines, than if they were just side by side.  The same goes with comparing with other modules.

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +                return Ok(handle
same comments as above on formatting, breaking this up with auto-formatting tools makes it harder to read IMHO

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +        let cmd = format!("zypper --non-interactive --quiet --table-style 10 search --match-exact --details --installed-only '{}'", self.package);
can you share what --table-style 10 does here?  It seems a bit strange to have a constant and I was curious if this was some sort of for-humans tabular mode that might not work with long package names.  I will absolutely test this myself manually before merging but figured I would just ask now.  Thanks!

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +        let skip_header = out.trim().lines().nth(2);
I would add some comments about what the nth(2) is expected to grab here, maybe you could include what the header looks like in a comment and that would help illustrate it?

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +#[cfg(test)]
please remove the test code from the module here.  It is very unlikely that these particular functions will fail and is more likely the command output itself would change, so we really incur the cost of keeping some extra unit test code around for little benefit.

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +        let cmd = format!("zypper --non-interactive --quiet --table-style 10 search --match-exact --details --installed-only '{}'", self.package);
I'm wondering can we do this without the table style?  Does it have a version where it prints things one per line more like the yum version?

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +                        changes.push(Field::Version);
this was reported recently in the apt module and I think we should go ahead and require this of all modules before we have too many modules to fix -- in the case of "update", we should check to see what the remote version will be, and if we are already at that version, we should not add it to changes.  The result of this is that it would only return a modification when there was a modification, which is important for check modes.  I have a ticket to fix this for apt and probably yum, and it probably also needs to be fixed in the submission for pacman, so... just wanted to let you know I'm not being overly picky since I know you copied it from my other stuff :)

2023-10-01 23:48 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +pub(crate) struct PackageDetails {
Minor -- we aren't using pub(crate) elsewhere, so I think it's fine to just say "pub"  -- I don't really want these to diverge between modules and I don't think there is any risk of someone importing it.  The alternative is to change everything but I'd rather see that happen later by me submitting another PR, if we needed to do it, which I think we don't.

2023-10-01 23:49 UTC, mpdehaan commented
Hi,

Thanks for this, I've added some comments to this one!  It appears we're rapidly getting a lot of modules copy and pasting that query body, so I probably need to make it something common before we get too many of these.  Not something we have to handle right now but something I'll probably do to update all of the package modules later this week assuming PRs get merged by then, if not, maybe a little later.

Thank you!

2023-10-02 01:09 UTC, bltavares commented on src/modules/packages/zypper.rs
> +        let cmd = format!("zypper --non-interactive --quiet --table-style 10 search --match-exact --details --installed-only '{}'", self.package);
I have not found a line-wise format without the table. I've added `style 10` as it seemed the easiest to parse.

Alternatively, there is a `--xmloutput` which should make the module more stable across changes of output, but would add more dependencies into the project.

2023-10-02 01:10 UTC, bltavares commented on src/modules/packages/zypper.rs
> +        let skip_header = out.trim().lines().nth(2);
I've added this output documentation as a test instead, that have the exact output to illustrate what is being parsed. Do you still prefer to use a comment instead?

2023-10-02 01:11 UTC, bltavares commented on src/modules/packages/zypper.rs
> +pub(crate) struct PackageDetails {
Given this was only added in order to allow the test to access it, I've added as a restrict access to this project, so external uses don't assume this is a public interface. If we remove the test, we can also avoid adding any `pub` declaration as it's done in other modules

2023-10-02 01:12 UTC, bltavares commented on src/modules/packages/zypper.rs
> +#[cfg(test)]
The tests were added as a way to document and illustrate the output of the search operation, and less to consider it may fail.

2023-10-02 01:14 UTC, bltavares commented
Hi there, I'll address the comments and update the PR then. As I'm not familiar with the direction of module inclusion on the project, I can also consider exposing this as an external module when the Tech Preview 2 is available, considering it's a package manager less used than the major projects.

2023-10-02 01:16 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +        let cmd = format!("zypper --non-interactive --quiet --table-style 10 search --match-exact --details --installed-only '{}'", self.package);
Yeah that's ok then! I wasn't familiar with Zypper output.

2023-10-02 01:17 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +        let skip_header = out.trim().lines().nth(2);
Yeah we don't have any trend of using unit tests like that and I think they instill a bit of false confidence and sometimes impair our ability to change API signatures.  Comment would be good, thanks!

2023-10-02 01:17 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +#[cfg(test)]
understood, yeah comment would be good, thank you!

2023-10-02 01:18 UTC, mpdehaan commented on src/modules/packages/zypper.rs
> +pub(crate) struct PackageDetails {
sounds good, I wasn't aware those weren't pub either, just wanted things to mostly be consistent.  thanks!

2023-10-03 17:56 UTC, bltavares commented
@mpdehaan thanks for the comments. I'll take a look again on this PR when I have more spare time during this week, if that is ok.

I can take the rebase to the other package manager modules myself, as well as adjusting the formatting to match the other files.

2023-10-03 18:25 UTC, mpdehaan commented
Yeah I'm more than happy to adapt it to the way yum/apt share code now, but if you'd like to before I get to it (likely this weekend), that would be fantastic thank very much!

I think the main thing is you may need to add a "get remote version" function, but if any package manager can't do that just return None from it, and it will still work fine.  Either yum or apt are good references, I think apt is a cleaner reference because we don't have that "is it yum or dnf" nonsense to do :)

Much appreciated!

2023-10-05 02:08 UTC, bltavares commented
@mpdehaan I've rebased with the main branch, and adjusted to the comments on the PR.

Let me know if you have more comments :)

2023-10-05 11:46 UTC, mpdehaan commented
sure thing, I will take a look at this probably this weekend!  I can probably make changes versus having to bounce back and forth for review, as I know SuSE folks would like to have this for sure!

2023-10-06 19:27 UTC, mpdehaan commented
I'm just testing some of the embedded zypper commands now to see what they return error code wise in the process of reviewing this module.  Using a fresh install from Linode, I found the following:

   zypper --non-interactive --quiet search --match-exact --details --installed-only tree; echo $?

Looking at the zypper module, I see the following in the (very long, lol) man page:


       104 - ZYPPER_EXIT_INF_CAP_NOT_FOUND
           Returned by the install and the remove command in case any of the arguments does not match any of the available (or installed) package names or
           other capabilities.


It seems the "None" needs to be returned only in the 104 case and the error conditions are errors, I'll make the change on this one.  Other review items in future comments....

2023-10-06 19:29 UTC, mpdehaan commented
This is on me, but there are multiple places with this:

     if result.is_ok() {
            let (rc,out) = cmd_info(&result.unwrap());
            if rc == 0 {
                let details = self.parse_zypper_search_table(&out)?;
                return Ok(details);
            } else {
                // FIXME: 
                return Ok(None);
            }
        } else {
            return Err(result.unwrap());
        }

The latter part should be result.unwrap_err() as the non error part of the result will be empty.

2023-10-06 19:31 UTC, mpdehaan commented
let details = self.parse_zypper_search_table(&out);

    let details = self.parse_zypper_search_table(&out)?;

use of "?" on the end of these is inconsistent, adding the "?" on both

2023-10-06 19:33 UTC, mpdehaan commented
tiny style thing:

   fn install_package(&self, handle: &Arc<TaskHandle>, request: &Arc<TaskRequest>) ->  Result<Arc<TaskResponse>,Arc<TaskResponse>>{

add space between type and "{"

2023-10-06 19:34 UTC, mpdehaan commented
minor style preference, be consistent and match the "good" scenario before the bad one:

          let row = match skip_header {
            // Not installed
            None => return Ok(None),
            Some(row) => row,
        };

VS right below it

        let details = match row.split("|").nth(3) {
            Some(version) => Some(PackageDetails {
                name: self.package.clone(),
                version: version.trim().to_string(),
            }),
            // shouldn't occur with rc=0, still don't want to call panic.
            None => None,
        };

2023-10-06 19:37 UTC, mpdehaan commented
the above function in question returned a result type but had no way to return an Error.  Now it will though, so I don't need to change it, but look for impossible return types in functions.

2023-10-06 19:41 UTC, mpdehaan commented
I see the logic of the yum and the apt module diverged in implementing some functions, I am going to rewrite apt so it uses "match" to avoid the unwrap vs unwrap_err problem that got introduced when this module copied the apt module.  And also update this to use match for the same ok vs error condition.

2023-10-06 19:46 UTC, mpdehaan commented
a lot of the things I'm commenting on come from the apt module, this is looking fine now and am cleaning up both, will have tested shortly :)

2023-10-06 20:09 UTC, merged

2023-10-06 20:09 UTC, mpdehaan commented
merged, thank you very much!

2023-10-06 20:39 UTC, bltavares commented
You are welcome :)