feat: Adding ArchLinux pacman module
jetporch/jetporch pull request #9
Opened 2023-09-30 04:47 UTC by enmanuelmoreira

2023-09-30 11:30 UTC, mpdehaan commented
Hi thanks very much for this, this was quick, awesome!... I need to set up Arch on (it looks like Linode may have arch images) and test this out, so this may be a few days.

I noticed the Name and Version parsing section still looked like yum's output, in the meantime, can you paste the output from a pacman info command for one package so I can see what it's scanning?  Nice if it's mostly the same.

Copyright should be "Jetporch project + contributors"

One thing I spotted is:

           if line.starts_with("error:") {
                 return Ok(None);
             }

It looks like the code can deal with the return code inside of get_package_details instead of looking for error strings in the output and that would be more robust.  Right now it appears to not do that.

Thank you!

2023-09-30 15:09 UTC, enmanuelmoreira commented
This is when the package is now installed on the system:
![image](https://github.com/jetporch/jetporch/assets/152518/60e74f65-a290-43bc-b17e-ad9afc25dd37)

And querying the package when installed:
![image](https://github.com/jetporch/jetporch/assets/152518/88ca2a49-9f3a-402e-a5f0-03bcf7f9ba5c)

2023-09-30 18:43 UTC, pcarinhas requested changes
Looks good.

2023-09-30 18:43 UTC, pcarinhas commented on src/modules/packages/pacman.rs
> +use serde::{Deserialize};
Remove braces on singleton import.

2023-09-30 18:56 UTC, mpdehaan commented on src/modules/packages/pacman.rs
> +use serde::{Deserialize};
Not a big deal, but yeah, I *suspect* this produces a warning and you do want to make sure there are no warnings in the output for any submissions, since it makes it easy to ignore warnings when there are other warnings.  If it didn't produce one, then I don't care :)

2023-09-30 19:00 UTC, mpdehaan commented
@enmanuelmoreira Thanks for output! yeah that looks good - since you're running in Spanish system do we need to do anything to the program generally to make it more reliable with programs that auto-localize?  

Most of the time, SSH not being set to a login shell I imagine we aren't getting localized output from pacman normally, which is good, but this is *not* true for the code path used when --forward-agent is used, as we have to manually execute SSH then.

I'm basically wondering if we need to add LANG=C to the ---forward-agent codepath, and if that's sufficient (yes?), and as it's been ages since I've done this I figured I'd ask if you knew.

Quick test is if running this command in your console with LANG=C prefixing the command makes it show up in English.

Thanks!

2023-09-30 20:42 UTC, enmanuelmoreira commented
After executing pacman -Q package:
![image](https://github.com/jetporch/jetporch/assets/152518/4beed194-4070-4df7-a67e-fb0dbb2a9da3)

2023-09-30 20:49 UTC, mpdehaan commented
great, that works as I remember, I will add that to the non-interactive version at least, if not both, that way pacman and others won't be broken in that mode.  (You don't have to add this I can do it everywhere in the ssh code internals).  Thanks!

2023-09-30 20:50 UTC, enmanuelmoreira commented
Nice! Thank you!

2023-09-30 20:52 UTC, mpdehaan commented
If you can see about adding that rc error check I can test and merge this one... I apologize for also not paying attention to the yum error code but I may have found it unreliable, can't remember!

2023-10-02 03:52 UTC, mpdehaan requested changes

2023-10-02 03:52 UTC, mpdehaan commented on src/modules/packages/pacman.rs
> +                        changes.push(Field::Version);
I mentioned this on other modules but ideally this should check the remote version and decide whether or not an update is required, as otherwise it will always attempt to run the update step.  I have this issue to fix in the existing yum and apt modules as well on my end, so this is my fault for having that problem there :)

2023-10-02 03:52 UTC, mpdehaan commented on src/modules/packages/pacman.rs
> +        let result = handle.remote.run(request, &cmd, CheckRc::Unchecked)?;
if the command returns non-zero on not found, you could possibly use the rc error code here and not check for the string "error" below.

2023-10-02 03:52 UTC, mpdehaan commented on src/modules/packages/pacman.rs
> +            if line.starts_with("error:") {
this was the check I was hoping could be replaced, also if there's a more specific string like "not found" maybe it should check for that if the return code is not useful?  I'm guessing there could be other types of errors?  what does the not found message look like?

2023-10-02 03:53 UTC, mpdehaan commented
Was still figuring out GitHub earlier, I have resubmitted this one "requesting changes" and added one small thing about checking to see if an update was needed with the update flag being set.

2023-10-02 16:02 UTC, mpdehaan commented
> Hi, I was doing the same thing and noticed some of my Archlinux machines does not have the `ID_LIKE` line :
> 
> ```
> $ grep ID /etc/os-release
> ID=arch
> BUILD_ID=rolling
> ```
> 
> On the screenshots it seems you are using EndeavourOS, I think, like Manjaro, they add the line. So I think you should base only on `ID=arch` !

I'm not going to let it block this one and we can see about that in a future PR if you want to go for it.

2023-10-02 21:56 UTC, mpdehaan commented
I just pushed a lot of new bits for the module code to make them more standardized but I think porting your PR over to this will be really easy.

I can take care of doing that and you don't need to do anything... it may be the later part of this week or next weekend, but will get it in soon, thank you!

2023-10-06 20:38 UTC, mpdehaan commented
I'm in the process of merging this one and will commit it regardless but it may need some fixing after the fact, one thing I see is that it doesn't pay attention to error codes from a few commands:

  let result = handle.remote.run(request, &cmd, CheckRc::Unchecked)?;
        let (_rc,out) = cmd_info(&result);
        let details = self.parse_package_details(&out.clone())?;
        return Ok(details);

I will take a look at man pages in a sec once I have an arch node up.

The parse package detail function is not written in a way that it could ever return an error.

2023-10-06 20:48 UTC, mpdehaan commented
testing this on linode I decided to try to install the tree package just manually:

[root@localhost ~]# pacman -S extra/tree --noconfirm --noprogressbar --needed

I get

error: failed retrieving file 'tree-2.1.0-1-x86_64.pkg.tar.zst' from mirrors.kernel.org : The requested URL returned error: 404

adding some other mirrors I'm also getting 404s so I guess there's a cache I don't know how to update

2023-10-06 21:29 UTC, merged